### ISSUE TITLE
Implement Save and Load State Functionality

### ISSUE THREAD

**Issue by tcarlsen** [CarlsnOP/moba-manager#12]
**Description:**
As MOBA Manager is an idle game, it's crucial to implement a save and load state system to ensure that a player's progress is preserved when they exit the game and return later. This feature should automatically save the game state at regular intervals and upon exiting, and load the saved state when the player returns to the game.

**Goals:**

- [x] Implement a system that automatically saves the game state at regular intervals.
- [x] Ensure the game state is saved when the player exits the game (including when the game is closed unexpectedly).
- [x] Develop a load state functionality that restores the player's progress when they return to the game.
~~- [ ] Save key data, including hero stats, progression, battle states, inventory, and current resources (XP, gold, loot).~~

**Considerations:**

- Consider using Godot's built-in methods for saving data, such as `File` or `ConfigFile`.
- Ensure data is saved in a way that can be easily extended in the future (e.g., adding new features or data points without breaking save files).
- Implement checks to prevent data corruption during saving/loading processes.

**Code Example:**

```gdscript
# Example of saving game state
func save_game_state():
    var save_file = File.new()
    if save_file.open("user://save_game.save", File.WRITE) == OK:
        var save_data = {
            "heroes": heroes,
            "resources": {"xp": total_xp, "gold": total_gold, "loot": loot_inventory},
            "current_battle": current_battle_state
        }
        save_file.store_var(save_data)
        save_file.close()

# Example of loading game state
func load_game_state():
    var save_file = File.new()
    if save_file.open("user://save_game.save", File.READ) == OK:
        var save_data = save_file.get_var()
        heroes = save_data["heroes"]
        total_xp = save_data["resources"]["xp"]
        total_gold = save_data["resources"]["gold"]
        loot_inventory = save_data["resources"]["loot"]
        current_battle_state = save_data["current_battle"]
        save_file.close()
```

**Comment by CarlsnOP** [comment]
All features has been added
Saves every 5 minutes.
Saves when user clicks "Quit game"
Saves when user clicks the "x" in the window
Saves when game crashes

Prevents the use of a save file if save file has been tempered with.

**Comment by CarlsnOP** [comment]
Done - waiting for items and spells
