### ISSUE TITLE
Implement In-Game Log Display on Main Screen

### ISSUE THREAD

**Issue by tcarlsen** [CarlsnOP/moba-manager#13]
**Description:**
Add a dynamic log on the main screen of the game that constantly updates with real-time events, such as the results of background battles, hero level-ups, item crafting, and other significant gameplay moments. This log will provide players with continuous feedback on the game’s progress, keeping them informed and engaged even while the game runs in idle mode.

**Goals:**

- [x] Design a UI element on the main screen that displays a scrolling log of recent game events.
- [x] Implement functionality to log important events such as:
  - Battle results (win/loss, participating heroes, damage dealt, rewards earned).
  - Hero level-ups (including which hero leveled up and their new stats).
  - Item crafting success/failure.
  - Any other significant gameplay events.
- [x] Ensure the log automatically scrolls as new events are added, with the most recent events displayed at the bottom.
- [x] Include the ability for players to pause, scroll, and clear the log if necessary.
- [x] Implement a system to manage the log’s length, potentially capping the number of entries to avoid performance issues.
- [x] Test the log across various screen sizes and ensure it displays correctly without overlapping other UI elements.

**Considerations:**

- Consider the visual design and placement of the log to ensure it is unobtrusive yet easily readable.
- The log should update smoothly without causing lag or stuttering, especially during intensive game events.
- Implement options in the settings menu to customize log behavior (e.g., toggle specific event types, adjust log size).

**Comment by tcarlsen** [comment]
UI Feedback so far

1. **Update Header Text:**
  - Change the main header from "Moba Manager" to "Battle Log" to better reflect the purpose of this page.
2. **Remove Subheader:**
  - The subheader "Rubber Duckies Earned" should be removed. The log should encompass more information than just the rubber duckies earned.
3. **Adjust Log Text Size:**
  - Reduce the font size of the log entries to allow more content to fit on the screen. The log should be able to display multiple battle outcomes, including detailed results from each match.
4. **Enhanced Log Content:**
  - The log should include more comprehensive information after each battle, such as:
    - **Outcome:** Whether the battle was won or lost.
    - **XP per Hero:** The amount of XP gained by each hero in the battle.
    - **Rubber Duckies Earned:** The number of rubber duckies earned.
    - **Loot:** Details of any loot acquired during the battle.
5. - Consider making the log scrollable if there are more entries than can fit on the screen. This ensures that players can review past battle outcomes easily.
6. **Highlight Important Events:**
  - Use subtle color-coding or icons to highlight significant events in the log, such as level-ups, rare loot drops, or particularly challenging battles.
7. **Clear Separators:**
  - Add clear separators between each battle entry to make the log easier to read and navigate.

**Comment by CarlsnOP** [comment]
Gonna create 2 logs, one battle log and another for general things.

**Battle log:**
- Enemy / friendly hero killed and by whom + at match time 
- Enemy / friendly tower killed and by whom + at match time
At nexus killed - reset log

**Event log:**
- Match over
 - match time
 - Outcome: Whether the battle was won or lost.
 - XP per Hero: The amount of XP gained by each hero in the battle.
 - Rubber Duckies Earned: The number of rubber duckies earned.
 - Loot: Details of any loot acquired during the battle.

**Comment by CarlsnOP** [comment]
Done! Celebrate wuhuuu
