### ISSUE TITLE
Add Hero: Eddy

### ISSUE THREAD

**Issue by tcarlsen** [CarlsnOP/moba-manager#21]
<img src="https://github.com/user-attachments/assets/4dc11fe4-13af-4f6d-88ca-658e36fe634d" width="300">

**Type:** Jungler

**Lore:**
Eddy was once just an ordinary kid with a love for exploring the wildest parts of the neighborhood. But one day, he stumbled upon a mysterious, enchanted scythe deep within a forgotten forest. The moment he touched it, Eddy was transformed into something... well, a bit crazier. Now, with a wicked grin permanently plastered on his face and a scythe that seems to have a mind of its own, Eddy roams the jungle like it’s his playground. He delights in ambushing unsuspecting foes, darting in and out of the shadows with wild laughter echoing behind him. Though his sanity might be questionable, his skills in the jungle are unmatched, and he’s always ready to leap into the fray when his team needs him most.

### Base Stats at Level 1

- **Health:** 550
- **Attack Damage (AD):** 60
- **Ability Power (AP):** 30

### Stat Growth Per Level

- **Health:** +80 per level
- **Attack Damage (AD):** +7 per level
- **Ability Power (AP):** +5 per level

**Comment by CarlsnOP** [comment]
Added Eddy
