### ISSUE TITLE
Add hero: Em

### ISSUE THREAD

**Issue by tcarlsen** [CarlsnOP/moba-manager#23]
<img src="https://github.com/user-attachments/assets/f5b68099-b142-41b1-9d75-09f7e377c701" width="300">

**Hero Type:** Marksman

**Lore:**
Em has always been a tinkerer with a passion for creating gadgets that go boom. From a young age, Em’s inventiveness got them into all sorts of trouble, but it also honed their skills with all things explosive. Armed with a custom-built water gun that packs a punch and a collection of homemade grenades, Em is a force to be reckoned with from a distance. Their infectious grin and boundless energy make them a lively addition to any team, always eager to show off the latest contraption and blow something up. Quick on their feet and quicker on the trigger, Em takes out enemies before they even know what hit them.

### Base Stats at Level 1

- **Health:** 500
- **Attack Damage (AD):** 70
- **Ability Power (AP):** 25

### Stat Growth Per Level

- **Health:** +70 per level
- **Attack Damage (AD):** +8 per level
- **Ability Power (AP):** +4 per level

**Comment by CarlsnOP** [comment]
Added Em
