### ISSUE TITLE
Add hero: Fred

### ISSUE THREAD

**Issue by tcarlsen** [CarlsnOP/moba-manager#24]
<img src="https://github.com/user-attachments/assets/d352ae5b-3a9f-41f8-afb1-dcdd3d269562" width="300">

**Hero Type:** Tank

**Lore:**
Fred was always the kid who loved playing the hero, but he took it one step further by crafting his own suit of armor from whatever he could find lying around. After years of refining his DIY knightly gear, Fred now marches into battle clad in an armor set that's as colorful as it is sturdy. With a shield that can block almost anything and an unwavering grin, Fred stands as the immovable wall between his team and any danger. His boundless enthusiasm and unshakable confidence make him the heart of any defense, inspiring his allies and frustrating his foes.

### Base Stats at Level 1

- **Health:** 800
- **Attack Damage (AD):** 50
- **Ability Power (AP):** 20

### Stat Growth Per Level

- **Health:** +110 per level
- **Attack Damage (AD):** +5 per level
- **Ability Power (AP):** +3 per level

**Comment by CarlsnOP** [comment]
Added Fred
