### ISSUE TITLE
Add hero: Todd

### ISSUE THREAD

**Issue by tcarlsen** [CarlsnOP/moba-manager#25]
<img src="https://github.com/user-attachments/assets/133a5c54-9d3a-4e45-9099-8e5dff2d2cf7" width="300">

**Hero Type:** Mage

**Lore:**
Todd has always been the oddball with his nose buried in books, particularly ones about magic. After stumbling upon an ancient tome of spells hidden away in the school library, Todd discovered he had a natural talent for the arcane arts. Now, with a hat that's too big for his head and a staff that seems a bit too powerful for his own good, Todd has set out to prove that brains (and a little bit of magic) can beat brawn any day. Though he may look a bit unsure at times, when it comes to casting spells, Todd’s power is nothing short of extraordinary.

### Base Stats at Level 1

- **Health:** 450
- **Attack Damage (AD):** 40
- **Ability Power (AP):** 80

### Stat Growth Per Level

- **Health:** +60 per level
- **Attack Damage (AD):** +4 per level
- **Ability Power (AP):** +12 per level

**Comment by CarlsnOP** [comment]
Added Todd
