### ISSUE TITLE
Add hero Lucy

### ISSUE THREAD

**Issue by tcarlsen** [CarlsnOP/moba-manager#28]
<img src="https://github.com/user-attachments/assets/106215f8-60b8-4fd3-87c5-6e7bd669eef8" width="300">

**Hero Type:** Support

**Lore:**
Lucy has always had a knack for mixing potions and concocting remedies that can cure just about anything. Her talent for healing started in her makeshift lab in the backyard, where she would mix ingredients from the garden to create powerful elixirs. Over time, her skills became legendary, and now she roams the battlefield with a bag full of potions, ready to heal and protect her allies. With a staff adorned with magical charms and an endless supply of restorative brews, Lucy is the glue that keeps her team alive through even the toughest of battles. Her cheerful demeanor and vibrant attire make her a beacon of hope, even in the direst of situations.

### Base Stats at Level 1

- **Health:** 520
- **Attack Damage (AD):** 35
- **Ability Power (AP):** 75

### Stat Growth Per Level

- **Health:** +65 per level
- **Attack Damage (AD):** +3 per level
- **Ability Power (AP):** +10 per level

**Comment by CarlsnOP** [comment]
Changed type from: Healer -> Support
Added Lucy
