### ISSUE TITLE
Implement Basic MOBA Battle Simulation

### ISSUE THREAD

**Issue by tcarlsen** [CarlsnOP/moba-manager#3]
**Description:**
Create the foundational code for simulating MOBA battles in Godot. This will involve setting up the logic for hero vs. hero battles, handling stats like Health, AD (Attack Damage), and AP (Ability Power), and integrating basic RNG for variation.

**Goals:**

- [x] Implement the battle simulation loop.
- [x] Include hero stats (Health, AD, AP).
- [x] Implement basic attack and defense mechanics.
- [x] Integrate RNG to simulate variability in battle outcomes.

Idea of how to implement: https://gist.github.com/tcarlsen/45a06dc8cd8b3962d8d19ec24d4bbd36

**Comment by CarlsnOP** [comment]
Added a match modifier in the new game script, that sets difficulty for every match between 0.8 and 1.2.
This modifier also affects rewards in rewards manager.
