### ISSUE TITLE
Add Hero Skills to MOBA Manager

### ISSUE THREAD

**Issue by tcarlsen** [CarlsnOP/moba-manager#30]
## Description:
This task involves adding the following skills to the respective heroes in the game. Each skill includes a name, a description of what the skill does, its base effect, and a section for upgrade effects.

All icons are inside the Skills folder on google drive, named after the skill.

### Eddy

- **Skill Name:** Loot Finder
- **Description:** Eddy has a nose for trouble—and treasure! His endless curiosity and sharp instincts make him a master of the jungle, where others might get lost, Eddy finds hidden stashes of loot that others would walk right past. With "Loot Finder," Eddy can sniff out even the most well-hidden treasures, ensuring that no chest, bag of gold, or shiny trinket goes unnoticed. Whether it’s behind a bush or under a rock, if there’s loot to be found, you can bet Eddy will find it, grinning ear to ear as he does.
- **Effect:** Loot amount is increased by 5%.
- **Upgrade Effects:** Increases the amount of loot Eddy finds in the jungle by 2%.

### Lucy

- **Skill Name:** Second Chance
- **Description:** Lucy’s magical concoctions are legendary, but there’s one potion she saves for only the direst of situations—her "Second Chance" elixir. When an ally is about to fall in battle, Lucy’s quick reflexes kick in, allowing her to toss this life-saving potion at them just in time. The result? The ally who would have otherwise met their demise is miraculously saved, surviving the encounter with a small portion of their health restored. This skill gives Lucy’s teammates the confidence to push forward, knowing that she’s got their back in the toughest of battles.
- **Effect:** Once per battle, when an ally is about to fall, Lucy automatically saves them, restoring 20% of their health.
- **Upgrade Effects:** Increases the amount of restored health by 5% per level, and the number of times she can do this in a battle increases by 1 every 2 skill levels.

### Em

- **Skill Name:** Explosive Finale
- **Description:** Em never goes down without making a big bang, and her "Explosive Finale" is the ultimate proof of that. When Em throws her specially crafted grenade, it detonates with tremendous force, dealing massive damage to her target. But the fun doesn’t stop there—there’s a chance that the explosion is so powerful, it sends shrapnel flying in all directions, hitting additional enemies nearby. While not guaranteed, when the shrapnel strikes true, it can turn the tide of a battle in an instant. This skill is all about high risk and high reward, just like Em herself!
- **Effect:** Em's grenade deals 150% of her AD as damage to the primary target, with a 50% chance to deal 50% of her AD as splash damage to nearby enemies.
- **Upgrade Effects:** Grenade damage percentage increases by 10% per level.

### Todd

- **Skill Name:** Mystic Overflow
- **Description:** Todd’s connection to the arcane is so deep that his magical energy sometimes overflows uncontrollably. "Mystic Overflow" taps into this excess power, causing Todd's spells to randomly surge during battle. Each time Todd casts a spell, there's a chance that his Ability Power (AP) to be amplified, causing him to deal significantly more damage. This skill is all about unpredictability, making Todd's magic both powerful and chaotic—perfectly embodying his eccentric wizardry.
- **Effect:** Each time Todd attacks, there is a 20% chance for his Ability Power to be amplified by 50% for that spell.
- **Upgrade Effects:** The chance for a amplified attack increases by 5% per level.

### Fred

- **Skill Name:** Ironclad Aura
- **Description:** Fred's armor isn't just for show—it's imbued with protective magic that radiates out to shield his allies. With "Ironclad Aura," Fred generates a powerful aura that reduces incoming damage for himself and nearby teammates during battles. While the effect isn’t constant, Fred’s aura can activate several times throughout a fight, providing crucial protection when it’s needed most.
- **Effect:** Fred’s aura reduces incoming damage by 20% for himself and nearby allies.
- **Upgrade Effects:** Damage reduction percentage increases by 4% per level.

### Egon

- **Skill Name:** Crushing Blow
- **Description:** Egon’s raw strength is legendary, and when he really puts his muscle into it, there’s no enemy that can stand in his way. With "Crushing Blow," Egon unleashes a devastating attack that deals massive extra damage. This skill represents Egon’s ability to land a hit so powerful, it can shatter defenses and leave opponents reeling. The impact of this blow is so intense that it has a chance to deal critical damage, making Egon’s presence on the battlefield impossible to ignore.
- **Effect:** Egon’s attack deals an additional 20% damage, with a chance to inflict critical damage.
- **Upgrade Effects:** Additional damage percentage increases by 4% per level.

**Comment by CarlsnOP** [comment]
Add all abilities without growth as prestige is not in game yet.
