### ISSUE TITLE
UI changes to Hero Page

### ISSUE THREAD

**Issue by tcarlsen** [CarlsnOP/moba-manager#31]
1. **Hero Description Alignment:**
  - [x] The hero description should be left-aligned instead of centered. This will improve readability and provide a cleaner look.
2. **Remove Plus Buttons on Stats:**
  - [x] The plus buttons next to the stats (Health, Attack Damage, and Ability Power) should be removed, as stats will now automatically increase with the hero's level.
3. **XP Progress Indicator:**
  - [x] Include a graphical element, such as a bar or a circular gauge, to visually display the remaining XP required for the next level. This will give players a clear and intuitive understanding of their progress.
4. **Increase Padding:**
  - [x] Add more padding on the left side to create a more spacious and aesthetically pleasing layout.
  - [x] Ensure there is consistent padding after all icons to maintain uniformity.
5. **Alignment of Name and Type:**
  - [x] The hero's name and type should be left-aligned with the description to create a cohesive and organized look.
  - [x] Consider explicitly labeling the fields as "Name," "Type," and "Description" to clarify the information being presented.
6. **Stat Icons:**
  - [x] The icons for Health, Attack Damage, and Ability Power should be uniformly sized and aligned with the corresponding text for a more polished appearance.

**Comment by CarlsnOP** [comment]
I believe I did the stuffs, tho I am no designer 👍
