### ISSUE TITLE
UI changes for Battle Setup Page

### ISSUE THREAD

**Issue by tcarlsen** [CarlsnOP/moba-manager#32]
1. **Lane Placement Adjustments:**  
  - The current setup should be reduced to only three placements: Top, Bottom, and Jungle.
2. **Remove Button:**
  - Include a "Remove" button next to each lane placement. This will allow players to easily remove heroes from their assigned lanes.
3. **Popup Window for Hero Selection:**
  - The selection popup should feel more like a true popup window:
    - Position it centrally on the screen.
    - Add a visible frame around the popup to distinguish it from the background.
    - Ensure that it clearly stands out as a separate UI element.
4. **Hero Information in Selection Popup:**
  - The popup should display all available heroes, including their names and levels.
  - Make sure that the text and icons are clearly visible and well-aligned, so players can quickly identify and select their heroes.

**Comment by CarlsnOP** [comment]
Defiantly still needs more work. But I want to move on with other things.
