### ISSUE TITLE
Develop Hero Stat and Progression System

### ISSUE THREAD

**Issue by tcarlsen** [CarlsnOP/moba-manager#4]
**Description:**
Implement the system for hero stats and progression. Each hero should have unique stats, and the system should support individual XP gain for leveling up and stat enhancement.

**Goals:**

- [x] Set up hero stats (Health, AD, AP).
- [x] Implement XP gain from battles.

**Code Example:**

```gdscript
func gain_xp(hero: Dictionary, xp_amount: int):
    hero["xp"] += xp_amount
    if hero["xp"] >= hero["xp_to_level"]:
        level_up(hero)

func level_up(hero: Dictionary):
    hero["level"] += 1
    hero["xp"] = 0
    hero["xp_to_level"] *= 1.5  # Example leveling curve
    hero["AD"] += 5  # Example stat increase
    hero["Health"] += 20
```

**Comment by tcarlsen** [comment]
@CarlsnOP  her is  a experience per level calculation:

### XP Formula:
\[ XP_{\text{required}}(n) = a \times n^2 + b \times n + c \]

Where:
- \( n \) is the level.
- \( a \), \( b \), and \( c \) are constants that you can adjust to control how quickly the XP requirements increase.

For example, let’s try:
- \( a = 10 \)
- \( b = 50 \)
- \( c = 100 \)

### XP Calculation for Level 1 to 99:
Let’s calculate the XP requirements for a few levels to see how this formula scales.

- **Level 1:** \( XP(1) = 10 \times 1^2 + 50 \times 1 + 100 = 160 \)
- **Level 10:** \( XP(10) = 10 \times 10^2 + 50 \times 10 + 100 = 1600 \)
- **Level 20:** \( XP(20) = 10 \times 20^2 + 50 \times 20 + 100 = 4500 \)
- **Level 50:** \( XP(50) = 10 \times 50^2 + 50 \times 50 + 100 = 28000 \)
- **Level 99:** \( XP(99) = 10 \times 99^2 + 50 \times 99 + 100 = 103050 \)

The XP requirements increase significantly as the level increases, which makes leveling up progressively harder.

**Comment by CarlsnOP** [comment]
Implemented a singleton to handle all leveling for heroes level_manager.
In order to generete level thresholds I used the following code:
for level in range(1, max_level + 1):
		current_exp += int(base_exp * pow(exp_multiplier, level - 1))
		exp_thresholds.append(current_exp)

to adjust, base_exp and exp_multipler can be changed.

stats gets assigned to heroes based on their current level * growth modifier.
