### ISSUE TITLE
Implement Item Crafting System

### ISSUE THREAD

**Issue by tcarlsen** [CarlsnOP/moba-manager#5]
**Description:**
Develop the item crafting system where players can craft and equip items to heroes. Items should modify hero stats (e.g., increase AD, AP, or Health).

**Goals:**

- [x] Create a system to handle item crafting based on loot drops.
- [x] Allow heroes to equip items and have those items affect their stats.
- [x] Implement a basic UI for crafting items.

**Code Example:**

```gdscript
func craft_item(materials: Dictionary) -> Dictionary:
    if materials["iron"] >= 10 and materials["wood"] >= 5:
        return {"name": "Iron Sword", "AD_bonus": 15}
    return {"name": "Failed Craft", "AD_bonus": 0}
    
func equip_item(hero: Dictionary, item: Dictionary):
    hero["items"].append(item)
    hero["AD"] += item["AD_bonus"]
```

**Comment by CarlsnOP** [comment]
Duplicate issue.

Done with this one
