### ISSUE TITLE
Design and Implement Basic UI

### ISSUE THREAD

**Issue by tcarlsen** [CarlsnOP/moba-manager#6]
**Description:**
Create a user interface for key game features, including hero management, battle placement, item crafting, and viewing hero stats.

**Goals:**

- [x] Design and implement UI for hero selection and placement on the battlefield.
- [x] Create an interface for item crafting and inventory management.
- [x] Display hero stats and progression in a clear, user-friendly way.

**Comment by CarlsnOP** [comment]
All features has been completed, more details in their individual issues.
