### ISSUE TITLE
Develop Reward System for Battle Outcomes

### ISSUE THREAD

**Issue by tcarlsen** [CarlsnOP/moba-manager#8]
**Description:**
Implement the system for distributing rewards based on battle outcomes. Rewards include XP, gold, and loot, with differences between wins and losses.

**Goals:**

- [x] Create a system to calculate and distribute rewards after battles.
- [x] Differentiate rewards based on victory or defeat.
- [x] Integrate with the crafting and progression systems.

**Code Example:**

```gdscript
func calculate_rewards(result: Dictionary) -> Dictionary:
    if result["win"]:
        result["xp"] = 100 + rng_range(0, 50)
        result["gold"] = 50 + rng_range(0, 30)
        result["loot"] = {"item": "Rare Item"}
    else:
        result["xp"] = 50 + rng_range(0, 20)
        result["gold"] = 20 + rng_range(0, 10)
        result["loot"] = {"item": "Common Item"}
    return result
```

Take some ideas from this maybe: https://gist.github.com/tcarlsen/45a06dc8cd8b3962d8d19ec24d4bbd36

**Comment by CarlsnOP** [comment]
**How I will setup reward system**
- [ ] rename currencymanager to rewardmanager

**Create modifiers**
- [ ] enemy team difficulity, random from game to game .8 to 1.2 
- [ ] rank modifier, higher rank higher modifier
- [ ] win modifier 2.0

**Setup what rewards will be given and base value, maybe rank sets base value?**
- [ ] rubberduckies
- [ ] hero exp
- [ ] loot

**How loot distribution will work**
- [ ] there will be a base threshold of loot you get every game, thay then gets increased with modifiers
- [ ] different rarities will have different weight, making common items appear more
- [ ] different rarities will have different values, lower rarity will have lower value. When an item is given the value will be substracted from the base threshold of loot received until all

**Comment by CarlsnOP** [comment]
Implemented full reward system with multipliers for rank, enemy difficulty multiplier and win multiplier. Rank is still to be setup but has been included in the system for easy implementation later
