### ISSUE TITLE
Implement Hero Placement System

### ISSUE THREAD

**Issue by tcarlsen** [CarlsnOP/moba-manager#9]
**Description:**
Create a system that allows players to place their heroes on the battlefield. This system should take into account the different lanes and the jungle, as well as the strategic importance of each position.

**Goals:**

- [x] Develop the UI for hero placement.
- [x] Implement the logic to handle hero positions and their impact on battle outcomes.
- [x] Allow players to adjust their strategy by moving heroes between positions.

**Comment by CarlsnOP** [comment]
Implemented the option to select which hero to put where. This is also saved in the TeamManager Singleton for when you close and open the game
